### ISSUE TITLE
GIF favourite hover star background

### ISSUE THREAD

**Issue by Yimura** [GeopJr/DNOME#3]
When hovering over a gif there is a star that becomes visible in the top right corner.
One of the wildcard selectors is causing a background to be added when the gif has already been favourited.

Themed:
![image](https://user-images.githubusercontent.com/24669514/108059100-4a89ad80-7055-11eb-9713-c51aee5f5355.png)

```css
/* All the classes on this star element */
.gifFavoriteButton-2SKrBk.size-3rN-gI.gifFavoriteButton-3Zycl7.selected-1mBDsA {

}

/* Selector from discord themselves */
.gifFavoriteButton-3Zycl7.selected-1mBDsA {
    color: #faa61a;
}
```

**Possible solution:**
Make the background transparent for this element.
==== or ====
Add corners to the background of this star but that would make this theme drift away from the native styling of Discord.
